# -*- coding: utf-8 -*-
"""2MongoAsses.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ME8pDIjs1NWvIiP5fAXdW_hSPREVyQCf
"""

!pip install dnspython
!pip install pymongo[srv]

"""Assignment 2
1 --->3 user inputs(name ,ph,email id)
2 --->3 inputs must be validated(name-capitalized,ph-10 numbers only,emaild id (unique)-mailid format)
3 --->insert it into mongodb and get(print) status (using try and exceptions(OPTIONAL))
"""

import pymongo
from pymongo import MongoClient
client = pymongo.MongoClient("mongodb+srv://username:pass@cluster0.eugde.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.nml
records=db.dcol1

Nam=input("Enter your Name:")
Phn=input("Enter your Mobile No:")
Maild=input("Enter Your Mail Id:")
Nam=Nam.capitalize()
if Phn.isdigit()==True and len(Phn)==10 and Maild.endswith("@gmail.com"):
  print("Name:",Nam)
  print("Mobile No:",Phn)
  print("Mail ID:",Maild)
  dct={'Name':Nam,'MobileNo':Phn,'Mailid':Maild}
  records.insert_one(dct)
else:
   print("Invalid Inputs try again")

